name: PyConES 2020
tagline: PyConES 2020<br />Pandemic Edition
date: 2 y 3 de octubre de 2020 (Online)
citation_date: 2 y 3 de octubre de 2020
#proceedings_title: PyConES 2020
analytics:
logo:
  image: static/images/logo-pycones2020.png
  width: 200px
  height: auto
site_title: PyConES 2020
page_title:
  prefix: PyConES 2020
  separator: ' - '
background_image: static/images/main.png
organization: Python España & PyConES 2020 Org

# Remove or change to your chat server.
# chat_server: miniconf.sloppy.zone
# default_presentation_id: 38922815
# default_poster_pdf: /static/images/GLTR_poster.pdf

# Configuration for auth
#Test user
#user: miniconf@miniconf.com
#pass: mIniconf1_

#use_auth0:
#auth0_client_id : JIdr6wi0z27LyLgwkJF0fpk700aj7MNH
#auth0_domain : miniconf.auth0.com

calendar:
  colors: #  Colors for the different event hashtags:
    org: '#b9b9b9'
    talk: '#2e88e1'
    workshop: '#eb9134'
    community: '#73bc64'
    assembly: '#f0c635'
  sunday_saturday: true  #  Include Sunday and Saturday
